experiment:
  name: "CLVTNet_EEG_AAD"
  seed: 42
  dataset: "KUL_DTU"
  device: "auto"
  num_workers: 4
  pin_memory: true

data:
  sampling_rate: 1024
  window_length: 2.0
  overlap: 0.5
  
  frequency_bands:
    alpha: [8.0, 12.0]
    beta: [13.0, 30.0]
    gamma: [30.0, 100.0]
  
  electrode_montage: "standard_1020"
  image_size: 256
  interpolation_method: "cubic"
  normalization: "z_score"
  artifact_removal: true
  filter_low: 0.5
  filter_high: 50.0
  notch_frequency: 50.0

model:
  name: "CLVTNet"
  input_channels: 1
  num_classes: 2
  image_size: 256
  
  embed_dims: [32, 80, 160, 256]
  num_heads: [2, 5, 10, 16]
  filter_sizes: [3, 5, 7, 9]
  num_blocks: [2, 2, 5, 2]
  
  dropout_rate: 0.1
  drop_path_rate: 0.1
  activation: "gelu"
  use_positional_encoding: true
  channel_attention_reduction: 16

training:
  batch_size: 64
  num_epochs: 300
  
  optimizer: "adam"
  learning_rate: 0.0003
  weight_decay: 0.05
  betas: [0.9, 0.999]
  eps: 1e-8
  
  scheduler: "cosine_annealing"
  warmup_epochs: 20
  warmup_lr: 0.00001
  min_lr: 0.00001
  
  criterion: "cross_entropy"
  label_smoothing: 0.1
  gradient_clipping: 1.0
  
  use_mixup: true
  mixup_alpha: 0.2
  use_cutmix: true
  cutmix_alpha: 1.0
  use_randaugment: true
  use_random_erasing: true
  augmentation_prob: 0.5
  
  early_stopping_patience: 20
  early_stopping_delta: 0.0001
  save_best_only: true
  save_frequency: 10
  validation_frequency: 1

evaluation:
  metrics: 
    - "accuracy"
    - "precision" 
    - "recall"
    - "f1_score"
    - "confusion_matrix"
  
  per_class_metrics: true
  generate_visualizations: true